from enum import Enum, unique
from tkinter.font import BOLD

@unique
class GrblError(Enum):
    BAD_G_CODE = 1
    BAD_NUMBER_FORMAT = 2
    INVALID_STATEMENT = 3
    VALUE_LESS_THAN_0 = 4
    HOMING_DISABLED = 5
    MINIMUM_STEP_PULSE_LESS_THAN_3 = 6
    EEPROM_READ_FAIL = 7
    NOT_IDLE = 8
    G_CODE_LOCK = 9
    HOMING_NOT_ENABLED = 10
    LINE_OVERFLOW = 11
    EXCEEDS_MAXIMUM_STEP_RATE = 12
    SAFETY_DOOR_OPEN = 13
    EXCEEDS_EEPROM_LINE_LIMIT = 14
    EXCEEDS_MACHINE_TRAVEL = 15
    INVALID_JOG_COMMAND = 16
    SETTING_DISABLED = 17
    UNSUPPORTED_COMMAND = 20
    MODAL_GROUP_VIOLATION = 21
    UNDEFINED_FEED_RATE = 22
    G_CODE_REQUIRES_INTEGER = 23
    G_CODE_MULTIPLE_COMMAND_REQUIRING_AXIS_WORDS = 24
    G_CODE_WORD_REPEATED = 25
    G_CODE_NO_AXIS_WORDS_FOUND = 26
    LINE_NUMBER_INVALID = 27
    G_CODE_MISSING_VALUE_WORD = 28
    G59_NOT_SUPPORTED = 29
    G53_NOT_ALLOWED = 30
    UNNECESSARY_AXIS_WORDS_FOUND = 31
    G2_G3_ARCS_REQUIRE_AXIS = 32
    MOTION_COMMAND_TARGET_INVALID = 33
    ARC_RADIUS_VALUE_INVALID = 34
    G2_G3_ARCS_REQUIRE_IN_PLANE_OFFSET = 35
    UNUSED_VALUE_WORDS_FOUND = 36
    INVALID_G43_TOOL_LENGTH_OFFSET = 37
    TOOL_NUMBER_EXCEEDS_MAX_VALUE = 38


@unique
class GrblAlarm(Enum):
    HARD_LIMIT = 1
    SOFT_LIMIT = 2
    POSITION_LOST = 3
    PROBE_FAIL_BAD_INITIAL = 4
    PROBE_FAIL_NO_CONTACT = 5
    HOMING_FAIL_RESET = 6
    HOMING_FAIL_DOOR_OPEN = 7
    HOMING_FAIL_BAD_PULLOFF = 8
    HOMING_FAIL_NO_LIMIT = 9
